# Github Actions: Despliegue Multi-Cloud
name: Deploy Multi-Cloud

on:
  push:
    branches:
      - main

jobs:
  deploy-azure:
    name: Deploy Azure Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy Bicep
        run: |
          az deployment group create \
            --resource-group ${{ secrets.AZURE_RG }} \
            --template-file azure/main.bicep \
            --parameters @environments/dev/azure-parameters.json

  deploy-aws:
    name: Deploy AWS Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Deploy Terraform AWS
        run: |
          cd aws
          terraform init
          terraform apply -var-file=../environments/dev/terraform.tfvars -auto-approve

  deploy-gcp:
    name: Deploy GCP Infra
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Deploy Terraform GCP
        run: |
          cd gcp
          terraform init
          terraform apply -var-file=../environments/dev/terraform.tfvars -auto-approve

  test-azure:
    name: Test AKS Azure
    runs-on: ubuntu-latest
    needs: deploy-azure
    steps:
      - uses: actions/checkout@v4
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Test AKS
        run: |
          chmod +x scripts/test-aks.sh
          ./scripts/test-aks.sh ${{ secrets.AZURE_RG }} aks-demo

  test-aws:
    name: Test AWS
    runs-on: ubuntu-latest
    needs: deploy-aws
    steps:
      - uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Test AWS
        run: |
          chmod +x scripts/test-aws.sh
          ./scripts/test-aws.sh

  test-gcp:
    name: Test GCP
    runs-on: ubuntu-latest
    needs: deploy-gcp
    steps:
      - uses: actions/checkout@v4
      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }}
      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
      - name: Test GCP
        run: |
          chmod +x scripts/test-gcp.sh
          ./scripts/test-gcp.sh
